name: Woolbattle
version: '${project.version}'
main: codes.Elix.Woolbattle.main.Woolbattle
api-version: 1.19
authors: [ N4med, Elix ]
description: This plugin is cool i guess?
depend:
  - FastAsyncWorldEdit

commands:
  setup:
  start:
  test:
  performance:
  countdown:
  all:
  setlive:
  build:
  hitted:
  debug:
  switchteam: