name: Woolbattle
version: '${project.version}'
main: codes.Elix.Woolbattle.main.Woolbattle
api-version: 1.19
authors: [ N4med, Elix ]
description: This plugin is cool i guess?

commands:
  setup:
  start:
  test:
  performance: