name: Woolbattle
version: 1.0
main: codes.Elix.Woolbattle.main.Woolbattle
api-version: 1.19
authors: [ N4med, Elix ]
description: Gamemode for Minecraft
depend:
  - FastAsyncWorldEdit
  #- TimoCloud

commands:
  setup:
  start:
  test:
  performance:
  countdown:
  all:
  setlive:
  build:
  hitted:
  debug:
  switchteam:
  fix:
  visualizewool: